params:
  - "title"
  - "icon"

canvas:
  width: 256
  height: 80
  antialias_size: 1    # 1-16 antialias range,The bigger the slower
  color: "#f93"  # "#XXX0" or "#XXXXXX00" 代表透明

items:
-
  type: "image"
  filename: "__icon__"
  pos:
    x: 16
    y: "center"
- 
  title: "__title__"
  type: "text"
  visible: true
  pos:
    x: 96
    y: "center"
  font:
    path: "/System/Library/fonts/Monaco.dfont"
    size: 24
    color: "#543"
        
-
  type: "shadow"
  alpha: 0.1
